name: easylivechat_sdk

packages:
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    run: melos exec -- "dart analyze --fatal-infos"
    description: Static-analyze every package.
  format:
    run: melos exec -- "dart format ."
  test:
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run tests in packages that have a test/ dir.
